version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - broker
      - db


  broker:
    hostname: rabbit
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
  worker:
    build: .
    command: ["celery","-A","config", "worker", "-l", "INFO"]
    volumes:
      - .:/code
    depends_on:
      - broker
      - db

  db:
    image: postgres:13-alpine

    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_username
      - POSTGRES_PASSWORD=my_password
